---
- name: Create AMQ Streams Operator
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: amq-streams
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: amq-streams
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        startingCSV: amqstreams.v2.9.1-1

- name: Wait for amq streams operator to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - name = amq-streams-cluster-operator
    wait: yes

- name: Create Kafka Cluster
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      metadata:
        name: my-cluster
        namespace: openshift-operators
      spec:
        kafka:
          config:
            default.replication.factor: 3
            inter.broker.protocol.version: "3.9"
            min.insync.replicas: 2
            offsets.topic.replication.factor: 3
            transaction.state.log.min.isr: 2
            transaction.state.log.replication.factor: 3
          listeners:
          - name: plain
            port: 9092
            tls: false
            type: internal
          - name: tls
            port: 9093
            tls: true
            type: internal
          replicas: 3
          storage:
            type: ephemeral
          version: 3.9.0
        zookeeper:
          replicas: 3
          storage:
            type: ephemeral

- name: Create Call Records Topic
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        name: call-records
        labels:
          strimzi.io/cluster: my-cluster
        namespace: openshift-operators
      spec:
        config:
          retention.ms: 604800000
          segment.bytes: 1073741824
        partitions: 10
        replicas: 3

- name: Create Dropped Alerts Topic
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaTopic
      metadata:
        name: dropped-alerts
        labels:
          strimzi.io/cluster: my-cluster
        namespace: openshift-operators
      spec:
        config:
          retention.ms: 604800000
          segment.bytes: 1073741824
        partitions: 10
        replicas: 3
# tasks file for amq-streams
